version: '3'
services:
    db: 
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: 139276
        POSTGRES_USER: 'admin'
        POSTGRES_DB: todo_db
      ports:
        - 5432:5432
      container_name: postgres_db
    